
package FoodOrderingSystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CustomerDashboard extends javax.swing.JFrame {

    private String CustomerID;
    private String custName;
    private String phoneNum;
    private boolean notiShown = false; // TO TRACK IF NOTIFICATION HAS BEEN SHOWN
    /**
     * Creates new form CustomerDashboard
     */
    public CustomerDashboard() {
        initComponents();
        this.CustomerID = "C01";
    }
    
    public CustomerDashboard(String CID){
        initComponents();
        this.CustomerID = CID;
    }
    
    private void readNotificationTxt(){
        try(BufferedReader br = new BufferedReader(new FileReader("Notification.txt"))){
            
            String read;
            boolean notificationCheck = false;
            
            DefaultTableModel model = (DefaultTableModel) NotificationTable.getModel();
            model.setRowCount(0);
            
            while((read = br.readLine()) != null){
                String[] data = read.split(";");
                
                String tempCustId = data[1];
                String notiAbout = data[2];
                String date = data[3];
                
                if(this.CustomerID.equalsIgnoreCase(tempCustId)){
                    model.addRow(new Object[]{
                        notiAbout, date
                    });
                    notificationCheck = true;
                }
                
            }
            
            if(!notificationCheck && !notiShown){
                JOptionPane.showMessageDialog(this, "There is no notification for you yet.", "System", JOptionPane.INFORMATION_MESSAGE);
                notiShown = true;
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Something wrong with your notification", "System", JOptionPane.INFORMATION_MESSAGE);
            notiShown = false;
        }
    }
    
    private boolean readCustomerProfile(){
        try(BufferedReader br = new BufferedReader(new FileReader("Customer Profile.txt"))){
            
            String read;           
            
            while((read = br.readLine()) != null){
                String[] data = read.split(";");
                
                String tempCustId = data[0];
                                
                if(this.CustomerID.equalsIgnoreCase(tempCustId)){
                    this.custName = data[2];
                    this.phoneNum = data[4];
                }
            }
                                   
            return true;
        }catch(IOException e){
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLbl = new javax.swing.JLabel();
        CloseBut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EditProfileBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        OrderMenuBtn = new javax.swing.JButton();
        OrderHistoryBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxnHistBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        OrderStatBtn = new javax.swing.JButton();
        OrderStatus = new javax.swing.JLabel();
        TopupCredit = new javax.swing.JLabel();
        RequestTopupAccBtn = new javax.swing.JButton();
        ReviewLbl = new javax.swing.JLabel();
        ComplaintBtn = new javax.swing.JButton();
        AppsNameLbl1 = new javax.swing.JLabel();
        AppsNameLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NotificationTable = new javax.swing.JTable();
        NotificationLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Dashboard");
        setName("Customer Dashboard"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        WelcomeLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WelcomeLbl.setText("Welcome *Customer*");
        WelcomeLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CloseBut.setText("Close");
        CloseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\APU YEAR 2 SEM 1\\OOP JAVA\\ASSIGNMENT\\profile2.png")); // NOI18N

        EditProfileBtn.setText("Edit Profile");
        EditProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\APU YEAR 2 SEM 1\\OOP JAVA\\ASSIGNMENT\\menu2.png")); // NOI18N

        OrderMenuBtn.setText("Menu");
        OrderMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderMenuBtnActionPerformed(evt);
            }
        });

        OrderHistoryBtn.setText("Order History");
        OrderHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderHistoryBtnActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\APU YEAR 2 SEM 1\\OOP JAVA\\ASSIGNMENT\\order history2.png")); // NOI18N

        TxnHistBtn.setText("Transaction History");
        TxnHistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxnHistBtnActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\APU YEAR 2 SEM 1\\OOP JAVA\\ASSIGNMENT\\txn2.png")); // NOI18N

        OrderStatBtn.setText("Order Status");
        OrderStatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderStatBtnActionPerformed(evt);
            }
        });

        OrderStatus.setIcon(new javax.swing.ImageIcon("E:\\APU YEAR 2 SEM 1\\OOP JAVA\\ASSIGNMENT\\order stat2.png")); // NOI18N

        TopupCredit.setBackground(new java.awt.Color(153, 255, 153));
        TopupCredit.setIcon(new javax.swing.ImageIcon("E:\\APU YEAR 2 SEM 1\\OOP JAVA\\ASSIGNMENT\\topup.png")); // NOI18N

        RequestTopupAccBtn.setText("Request Topup");
        RequestTopupAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestTopupAccBtnActionPerformed(evt);
            }
        });

        ReviewLbl.setIcon(new javax.swing.ImageIcon("E:\\APU YEAR 2 SEM 1\\OOP JAVA\\GUIProject\\Assignment\\src\\Customer\\img\\icons8-review-50.png")); // NOI18N

        ComplaintBtn.setText("Complaints");
        ComplaintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplaintBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderStatus)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OrderMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderStatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TopupCredit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RequestTopupAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(ReviewLbl))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComplaintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxnHistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RequestTopupAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TopupCredit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(TxnHistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OrderMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OrderHistoryBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComplaintBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReviewLbl)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OrderStatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderStatus))
                .addGap(42, 42, 42))
        );

        AppsNameLbl1.setFont(new java.awt.Font("STCaiyun", 1, 48)); // NOI18N
        AppsNameLbl1.setText("JOM");

        AppsNameLbl.setFont(new java.awt.Font("STCaiyun", 1, 48)); // NOI18N
        AppsNameLbl.setText("MAKAN");

        NotificationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "About", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(NotificationTable);
        if (NotificationTable.getColumnModel().getColumnCount() > 0) {
            NotificationTable.getColumnModel().getColumn(0).setResizable(false);
            NotificationTable.getColumnModel().getColumn(1).setResizable(false);
        }

        NotificationLbl.setText("NOTIFICATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CloseBut))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(WelcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AppsNameLbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(AppsNameLbl1)))
                                .addGap(71, 71, 71)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(NotificationLbl)))))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeLbl)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(AppsNameLbl1)
                                .addGap(69, 69, 69)
                                .addComponent(AppsNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(CloseBut)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NotificationLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileBtnActionPerformed
        EditProfile EP = new EditProfile(this.CustomerID);
        EP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditProfileBtnActionPerformed

    private void OrderMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderMenuBtnActionPerformed

        VendorList VL = new VendorList(this.CustomerID);
        this.setVisible(false);
        VL.setLocationRelativeTo(null);
        VL.setVisible(true);
    }//GEN-LAST:event_OrderMenuBtnActionPerformed

    private void OrderHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderHistoryBtnActionPerformed
        OrderHistory OH = new OrderHistory(this.CustomerID);
        OH.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OrderHistoryBtnActionPerformed

    private void TxnHistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxnHistBtnActionPerformed
        TransactionHistory TH = new TransactionHistory(this.CustomerID);
        TH.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TxnHistBtnActionPerformed

    private void OrderStatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderStatBtnActionPerformed
        OrderStatus OS = new OrderStatus(this.CustomerID);
        this.setVisible(false);
        OS.setVisible(true);
    }//GEN-LAST:event_OrderStatBtnActionPerformed

    private void CloseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButActionPerformed
        Login L = new Login();
        this.setVisible(false);
        L.setVisible(true);
    }//GEN-LAST:event_CloseButActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
        WelcomeLbl.setText("Welcome " + this.CustomerID);
        this.setLocationRelativeTo(null);
        System.out.println(this.CustomerID);
        readNotificationTxt();
    }//GEN-LAST:event_formWindowActivated

    private void RequestTopupAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestTopupAccBtnActionPerformed
        RequestTopup RT = new RequestTopup(this.CustomerID);
        RT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RequestTopupAccBtnActionPerformed

    private void ComplaintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplaintBtnActionPerformed
        if(readCustomerProfile()){
            Complaint C = new Complaint(this.CustomerID, this.custName,this.phoneNum);
            this.setVisible(false);
            C.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "System in maintenance. Please contact administrator.", "System", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_ComplaintBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppsNameLbl;
    private javax.swing.JLabel AppsNameLbl1;
    private javax.swing.JButton CloseBut;
    private javax.swing.JButton ComplaintBtn;
    private javax.swing.JButton EditProfileBtn;
    private javax.swing.JLabel NotificationLbl;
    private javax.swing.JTable NotificationTable;
    private javax.swing.JButton OrderHistoryBtn;
    private javax.swing.JButton OrderMenuBtn;
    private javax.swing.JButton OrderStatBtn;
    private javax.swing.JLabel OrderStatus;
    private javax.swing.JButton RequestTopupAccBtn;
    private javax.swing.JLabel ReviewLbl;
    private javax.swing.JLabel TopupCredit;
    private javax.swing.JButton TxnHistBtn;
    private javax.swing.JLabel WelcomeLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
