package FoodOrderingSystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class HomepageRunner extends javax.swing.JFrame {

    /**
     * Creates new form RevenueDashboard
     */
    
    private String runnerId;
    
    public HomepageRunner() {
        initComponents();
        checkRunnerTask(runnerId);
    }
    
    public HomepageRunner(String RunnerID){
        initComponents();
        this.runnerId = RunnerID;
        checkRunnerTask(this.runnerId);
    }
    
    private void checkRunnerTask(String runnerID) {
        String filename = "Order Status.txt"; // Ensure this file exists
        boolean hasPendingTask = false;

        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(";");

                // Ensure valid row format and check if the runner ID matches
                if (data.length >= 12 && data[2] != null && data[2].equalsIgnoreCase(runnerID)) {
                    String status = data[11]; // Status column index

                    // ✅ If status is NOT "Completed", notify the runner
                    if (!status.equalsIgnoreCase("Completed")) {
                        hasPendingTask = true;
                        break; // Exit loop early once an incomplete task is found
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error loading file: " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ✅ Show appropriate message based on task status
        if (hasPendingTask) {
            JOptionPane.showMessageDialog(null, "You have a pending task!", "Task Notification", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Currently, you don't have any pending tasks.", "Task Notification", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RevenueDashborad = new javax.swing.JButton();
        CurrentTask = new javax.swing.JButton();
        TaskHistory = new javax.swing.JButton();
        EditProfilebutton = new javax.swing.JButton();
        LogOutbutton = new javax.swing.JButton();
        Reviewbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Runner Homepage");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Homepage");

        RevenueDashborad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RevenueDashborad.setText("Revenue Dashboard");
        RevenueDashborad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenueDashboradActionPerformed(evt);
            }
        });

        CurrentTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CurrentTask.setText("Current Task");
        CurrentTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentTaskActionPerformed(evt);
            }
        });

        TaskHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TaskHistory.setText("Task History");
        TaskHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskHistoryActionPerformed(evt);
            }
        });

        EditProfilebutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditProfilebutton.setText("Edit Profile");
        EditProfilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfilebuttonActionPerformed(evt);
            }
        });

        LogOutbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LogOutbutton.setText("Logout");
        LogOutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutbuttonActionPerformed(evt);
            }
        });

        Reviewbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Reviewbutton.setText("Review");
        Reviewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TaskHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RevenueDashborad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrentTask, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Reviewbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditProfilebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(LogOutbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(CurrentTask, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Reviewbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditProfilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogOutbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(RevenueDashborad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RevenueDashboradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenueDashboradActionPerformed
        RevenueDashboard RD = new RevenueDashboard(this.runnerId);
        RD.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RevenueDashboradActionPerformed

    private void CurrentTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentTaskActionPerformed
        CurrentTask CT = new CurrentTask(this.runnerId);
        CT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CurrentTaskActionPerformed

    private void TaskHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskHistoryActionPerformed
        TaskHistory TH = new TaskHistory(this.runnerId);
        TH.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TaskHistoryActionPerformed

    private void EditProfilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfilebuttonActionPerformed
        EditProfileRunner EPR = new EditProfileRunner(this.runnerId);
        EPR.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditProfilebuttonActionPerformed

    private void LogOutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutbuttonActionPerformed

    private void ReviewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewbuttonActionPerformed
        RunnerReview TH = new RunnerReview(this.runnerId);
        TH.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReviewbuttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomepageRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomepageRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomepageRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomepageRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomepageRunner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CurrentTask;
    private javax.swing.JButton EditProfilebutton;
    private javax.swing.JButton LogOutbutton;
    private javax.swing.JButton RevenueDashborad;
    private javax.swing.JButton Reviewbutton;
    private javax.swing.JButton TaskHistory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
