/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FoodOrderingSystem.Manager;

/**
 *
 * @author Teoh Peng Kee
 */
public class HomePageManager extends javax.swing.JFrame {

    /**
     * Creates new form HomePageManager
     */
    public HomePageManager() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CurrentTask1 = new javax.swing.JButton();
        btnManageVendorItems = new javax.swing.JButton();
        btnVendorDB = new javax.swing.JButton();
        btnRunnerDB = new javax.swing.JButton();
        btnManageComplaints = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Homepage");

        CurrentTask1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CurrentTask1.setText("Logout");
        CurrentTask1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentTask1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CurrentTask1)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CurrentTask1)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnManageVendorItems.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManageVendorItems.setText("Manage Vendor Items");
        btnManageVendorItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVendorItemsActionPerformed(evt);
            }
        });

        btnVendorDB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVendorDB.setText("Vendor Dashboard");
        btnVendorDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendorDBActionPerformed(evt);
            }
        });

        btnRunnerDB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRunnerDB.setText("Runner Dashboard");
        btnRunnerDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunnerDBActionPerformed(evt);
            }
        });

        btnManageComplaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManageComplaints.setText("Manage Complaints");
        btnManageComplaints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageComplaintsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVendorDB, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageVendorItems, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRunnerDB, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageComplaints, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnVendorDB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnRunnerDB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnManageComplaints, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnManageVendorItems, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurrentTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentTask1ActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_CurrentTask1ActionPerformed

    private void btnVendorDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendorDBActionPerformed
	// TODO add your handling code here:
	this.dispose();
	new VendorDashboard().setVisible(true);
    }//GEN-LAST:event_btnVendorDBActionPerformed

    private void btnRunnerDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunnerDBActionPerformed
	// TODO add your handling code here:
	this.dispose();
	new RunnerDashboard().setVisible(true);
    }//GEN-LAST:event_btnRunnerDBActionPerformed

    private void btnManageComplaintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageComplaintsActionPerformed
	// TODO add your handling code here:
	this.dispose();
	new ManageComplaintsPage().setVisible(true);
    }//GEN-LAST:event_btnManageComplaintsActionPerformed

    private void btnManageVendorItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVendorItemsActionPerformed
	// TODO add your handling code here:
	this.dispose();
	new ManageVendorItemsPage().setVisible(true);
    }//GEN-LAST:event_btnManageVendorItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(HomePageManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(HomePageManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(HomePageManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(HomePageManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new HomePageManager().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CurrentTask1;
    private javax.swing.JButton btnManageComplaints;
    private javax.swing.JButton btnManageVendorItems;
    private javax.swing.JButton btnRunnerDB;
    private javax.swing.JButton btnVendorDB;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
